# Generated by Django 3.2.17 on 2023-03-03 17:52

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Máximo 50 caracteres', max_length=50, verbose_name='Título')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Valor mensal do imóvel', max_digits=8, verbose_name='Preço')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='cadastros', variations={'thumb': (124, 124)}, verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('rua', models.CharField(max_length=50, verbose_name='Rua')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('cep', models.CharField(max_length=100, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Edificío',
                'verbose_name_plural': 'Edificíos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=25, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=25, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.CharField(help_text='Máximo 16 caracteres', max_length=16, verbose_name='Telefone')),
                ('cpf', models.CharField(help_text='Máximo 16 caracteres', max_length=16, verbose_name='CPF')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartamento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AddField(
            model_name='apartamento',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.edificio'),
        ),
    ]
