# Generated by Django 4.1.7 on 2023-03-06 17:53

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Máximo 50 caracteres', max_length=50, verbose_name='Título')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Valor mensal do imóvel', max_digits=8, verbose_name='Preço')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('numero_quartos', models.IntegerField(verbose_name='Número de quartos')),
                ('numero_banheiros', models.IntegerField(verbose_name='Número de banheiros')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='cadastros', variations={'thumb': (280, 280)}, verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('alugado', models.BooleanField(default=False, verbose_name='Alugado')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('rua', models.CharField(max_length=50, verbose_name='Rua')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Edificío',
                'verbose_name_plural': 'Edificíos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=25, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('cpf', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='CPF')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartamento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AddField(
            model_name='apartamento',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.edificio'),
        ),
    ]
