# Generated by Django 4.1.7 on 2023-03-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
