# Generated by Django 4.1.7 on 2023-03-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_edificio_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
